Add missing require
    ActionView::Template::Error - undefined method `with_indifferent_access' for {:word=>""}:Hash:
          /.../gems/2.4.0/gems/kaminari-core-1.0.1/lib/kaminari/helpers/tags.rb:25:in `initialize'